### ISSUE TITLE
auth access

### ISSUE THREAD

**Issue by mybigman** [pwntr/samba-alpine-docker#2]
How do I access the share via they credentials to be able to write.

I can access the share as read without problems.

I tried mapping the network with rio/letsdance but was denied

**Comment by mybigman** [comment]
needed - ntlm auth = yes

**Comment by pwntr** [comment]
Interesting find, thx for sharing and closing! Can you elaborate on what kind of client you used for accessing the server? I suspect a rather old one that needed NTLMv1 auth to be provided (according to [the samba documentation](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html))?
