### ISSUE TITLE
Is there a way to add more shares?

### ISSUE THREAD

**Issue by wsw70** [pwntr/samba-alpine-docker#3]
I see that `/shared` inside the container can be mapped to a host folder to be shared.

Is there a way to add more shares?

**Comment by pwntr** [comment]
Yes, absolutely! You only need to add the new shares to the `smb.conf`, analog to the `[data]` share, and add more volume mappings to the docker run command (`docker run -d --network host -v /path/to/share/:/shared -v /path/to/share2/:/shared2 -v /path/to/share3/:/shared3 -v /path/to/share4/:/shared4 --name samba pwntr/samba-alpine` and so on).

I'm not 100% sure if the target directories that you map to need to exist on `smb` process start, which might be the case. Then you'd also need to rebuild the container by first creating the target directories inside the Dockerfile. But it could just as well be the case that they're created dynamically on container start, which precedes the process start itself.

I'd say give it a try and report back :)!
